# users/api/views.py
#
# Database: MySQL  ← all raw SQL here is MySQL-compatible.
#
# Key MySQL rules followed throughout this file:
#   - Parameterised values always use %s  (MySQLdb/mysqlclient style)
#   - LAST_INSERT_ID() used after every INSERT to get the new PK
#     (safe and atomic — it returns the ID generated by *this* connection,
#      so concurrent inserts from other connections never interfere)
#   - No RETURNING clause (PostgreSQL-only — not supported by MySQL)
#   - TINYINT(1) used for booleans  (MySQL has no native BOOLEAN type;
#     Django stores BooleanField as tinyint(1), so we pass 0/1)
#   - String literals use single quotes in SQL, %s for parameters
#   - LIMIT without OFFSET written as LIMIT n  (MySQL syntax)
#
# Single RegisterView handles ALL roles: CUSTOMER, RIDER, RESTAURANT.
# Rider registration also inserts into:
#   - addresses_address                    (the rider's home address)
#   - riders_rider                         (core rider profile)
#   - riders_rider_additional_information  (NID, wallet, emergency contact)
#
# insert_address() is a standalone helper so any other view can reuse it.

from datetime import datetime
from django.contrib.auth.hashers import make_password, check_password
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework_simplejwt.views import TokenObtainPairView
from django.db import connection, IntegrityError, transaction

from ..models import User
from .serializers import UserRegistrationSerializer, MyTokenObtainPairSerializer
from riders.api.services import validate_rider_fields, insert_rider
from customers.api.services import insert_customer
from resturants.api.services import insert_restaurant


# ─────────────────────────────────────────────────────────────────────────────
# REGISTRATION — one view for every role
# ─────────────────────────────────────────────────────────────────────────────

class RegisterView(APIView):
    """
    POST /api/auth/register/

    Handles sign-up for CUSTOMER, RIDER, and RESTAURANT roles.
    The 'role' field in the request body decides what extra tables get populated.

    ── Common fields (all roles) ──────────────────────────────────────────────
    {
        "first_name":   "John",
        "last_name":    "Doe",
        "email":        "john@example.com",
        "phone_number": "01712345678",
        "password":     "secret123",
        "password2":    "secret123",
        "role":         "RIDER"          # CUSTOMER | RIDER | RESTAURANT
    }

    ── Extra fields for RIDER  (send as multipart/form-data, NOT JSON) ────────
    {
        "vehicle":                  "BIKE",          # BIKE | CYCLE | SCOOTER
        "license_plate":            "DHA-1234",
        "street_address":           "Road 4, Block B",
        "city":                     "Dhaka",
        "latitude":                 23.780,          # optional
        "longitude":                90.420,          # optional
        "nid_number":               "1234567890",
        "gender":                   "Male",
        "wallet_balance":           0.00,            # optional, defaults to 0
        "emergency_contact_name":   "Jane Doe",
        "emergency_contact_number": "01798765432",
        // nid_front, nid_back → image files in multipart body
    }

    ── Extra fields for RESTAURANT ────────────────────────────────────────────
    {
        "restaurant_name":     "Kutumbari Restora",
        "restaurant_category": "RESTAURANT"          # optional
    }
    """
    permission_classes = [AllowAny]

    def post(self, request):
        print(request.data)
        # ── Step 1: validate base user fields via existing serializer ───────
        serializer = UserRegistrationSerializer(data=request.data)
        if not serializer.is_valid():
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

        # ── Step 2: extract validated common fields ──────────────────────────
        email        = serializer.validated_data['email']
        password     = make_password(serializer.validated_data['password'])
        phone_number = serializer.validated_data.get('phone_number', '')
        role         = serializer.validated_data.get('role', 'CUSTOMER')
        first_name   = serializer.validated_data.get('first_name', '')
        last_name    = serializer.validated_data.get('last_name', '')

        # MySQL stores BooleanField as TINYINT(1) — pass integers, not True/False
        is_superuser = 0
        is_staff     = 0
        is_active    = 1
        date_joined  = datetime.now()  # MySQL DATETIME — Python datetime works fine

        # ── Step 3: role-specific validation BEFORE touching the DB ─────────
        if role == 'RIDER':
            error_msg = validate_rider_fields(request.data, request.FILES)
            if error_msg:
                return Response({"error": error_msg}, status=status.HTTP_400_BAD_REQUEST)

        elif role == 'RESTAURANT':
            if not request.data.get('restaurant_name', '').strip():
                return Response(
                    {"error": "restaurant_name is required for Restaurant registration."},
                    status=status.HTTP_400_BAD_REQUEST
                )

        # ── Step 4: all DB inserts in a single atomic transaction ────────────
        # transaction.atomic() on MySQL uses InnoDB savepoints.
        # Any exception inside rolls back every INSERT in this block.
        try:
            with transaction.atomic():
                with connection.cursor() as cursor:
                    # 4a ── Insert the base users_user row ───────────────────
                    cursor.execute(
                        """
                        INSERT INTO users_user
                            (password, is_superuser, email, is_staff, is_active,
                             date_joined, role, phone_number, image_url,
                             first_name, last_name)
                        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                        """,
                        [
                            password, is_superuser, email, is_staff, is_active,
                            date_joined, role, phone_number, '',
                            first_name, last_name,
                        ]
                    )

                    # Use LAST_INSERT_ID() — atomic and connection-scoped in MySQL.
                    # Never use SELECT WHERE email here; another thread could
                    # INSERT the same email between our INSERT and SELECT.
                    cursor.execute("SELECT LAST_INSERT_ID()")
                    row = cursor.fetchone()
                    if not row or not row[0]:
                        raise Exception("MySQL did not return a valid user ID after INSERT.")
                    new_user_id = row[0]

                    # 4b ── Role-specific child table inserts ─────────────────
                    if role == 'CUSTOMER':
                        insert_customer(cursor, new_user_id)

                    elif role == 'RIDER':
                        # Cloudinary uploads happen inside this method.
                        # If an upload fails it raises, which triggers rollback.
                        insert_rider(cursor, new_user_id, request)

                    elif role == 'RESTAURANT':
                        insert_restaurant(
                            cursor, new_user_id, phone_number, request.data
                        )

            return Response(
                {"message": f"{role.capitalize()} registered successfully"},
                status=status.HTTP_201_CREATED
            )

        except IntegrityError:
            # MySQL raises IntegrityError for duplicate UNIQUE keys
            # (email or phone_number in this case)
            return Response(
                {"error": "A user with this email or phone number already exists."},
                status=status.HTTP_400_BAD_REQUEST
            )
        except Exception as e:
            return Response({"error": str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
    

    


# ─────────────────────────────────────────────────────────────────────────────
# LOGIN — unchanged, uses existing serializer
# ─────────────────────────────────────────────────────────────────────────────

class MyLoginView(TokenObtainPairView):
    """
    POST /api/auth/login/
    Uses MyTokenObtainPairSerializer (already written) which adds
    role + user info to the JWT payload.
    No changes needed here.
    """
    serializer_class = MyTokenObtainPairSerializer


# ─────────────────────────────────────────────────────────────────────────────
# USER PROFILE — unchanged, returns role-specific data
# ─────────────────────────────────────────────────────────────────────────────

def format_time(val):
    """Convert MySQL TimeField value (timedelta or time or string) to HH:MM string."""
    if val is None:
        return None
    if hasattr(val, 'seconds'):  # timedelta from MySQL
        total = int(val.total_seconds())
        h, m = divmod(total // 60, 60)
        return f"{h:02d}:{m:02d}"
    return str(val)[:5]  # already a string or time object — take first 5 chars "HH:MM"


class UserProfileView(APIView):
    """
    GET /api/auth/profile/
    Returns the logged-in user's profile.
    For RIDER role, now also returns the additional info (NID, emergency, wallet).
    """
    permission_classes = [IsAuthenticated]

    def get(self, request):
        user_id       = request.user.id
        response_data = {}

        with connection.cursor() as cursor:

            # ── Base user row ──────────────────────────────────────────────
            cursor.execute("""
                SELECT first_name, last_name, email,
                       phone_number, role, image_url
                FROM users_user
                WHERE id = %s
            """, [user_id])
            user_row = cursor.fetchone()

            if not user_row:
                return Response(
                    {"error": "User not found"},
                    status=status.HTTP_404_NOT_FOUND
                )

            response_data = {
                "first_name":   user_row[0],
                "last_name":    user_row[1],
                "email":        user_row[2],
                "phone_number": user_row[3],
                "role":         user_row[4],
                "image_url":    user_row[5],
            }
            role = response_data['role']

            # ── Role-specific extra data ───────────────────────────────────

            if role == 'CUSTOMER':
                cursor.execute("""
                    SELECT wallet_balance
                    FROM customers_customer
                    WHERE user_id = %s
                """, [user_id])
                row = cursor.fetchone()
                response_data["wallet_balance"] = row[0] if row else 0.00

            elif role == 'RIDER':
                # Core profile
                cursor.execute("""
                    SELECT id, is_available, vehicle, license_plate,
                           current_latitude, current_longitude
                    FROM riders_rider
                    WHERE user_id = %s
                """, [user_id])
                rider_row = cursor.fetchone()

                if rider_row:
                    rider_id = rider_row[0]
                    response_data["rider_info"] = {
                        "is_available":    bool(rider_row[1]),
                        "vehicle":         rider_row[2],
                        "license_plate":   rider_row[3],
                        "current_lat":     rider_row[4],
                        "current_lng":     rider_row[5],
                    }

                    # Additional info
                    cursor.execute("""
                        SELECT
                            rai.nid_number,
                            rai.gender,
                            rai.wallet_balace,
                            rai.emergency_contact_name,
                            rai.emergency_contact_number,
                            a.street_address,
                            a.city,
                            a.latitude,
                            a.longitude
                        FROM riders_rider_additional_information rai
                        LEFT JOIN addresses_address a ON a.address_id = rai.address_id
                        WHERE rai.rider_id = %s
                    """, [rider_id])
                    add_row = cursor.fetchone()

                    if add_row:
                        response_data["rider_additional_info"] = {
                            "nid_number":               add_row[0],
                            "gender":                   add_row[1],
                            "wallet_balance":           str(add_row[2]),
                            "emergency_contact_name":   add_row[3],
                            "emergency_contact_number": add_row[4],
                            "address": {
                                "street_address": add_row[5],
                                "city":           add_row[6],
                                "latitude":       add_row[7],
                                "longitude":      add_row[8],
                            }
                        }

            elif role == 'RESTAURANT':
                cursor.execute("""
                    SELECT id, name, restaurant_category, rating,
                           phone, opening_time, closing_time, image_url
                    FROM resturants_restaurant
                    WHERE user_id = %s
                    LIMIT 1
                """, [user_id])
                row = cursor.fetchone()
                if row:
                    response_data["restaurant_info"] = {
                        "id":               row[0],
                        "restaurant_name":  row[1],
                        "category":         row[2],
                        "rating":           row[3],
                        "contact_phone":    row[4],
                        "opening_time":     format_time(row[5]),
                        "closing_time":     format_time(row[6]),
                        "restaurant_image": row[7],
                    }

        return Response(response_data)
    def patch(self, request):
        """
        PATCH /api/auth/profile/
        Updatable fields: first_name, last_name, phone_number, password.
        All fields are optional — only provided fields are updated.
        For password change, current_password must also be supplied.
        """
        user_id = request.user.id
        data    = request.data

        # ── 1. Collect which updatable fields were sent ──
        ALLOWED_FIELDS = {'first_name', 'last_name', 'phone_number'}
        updates = {field: data[field] for field in ALLOWED_FIELDS if field in data}

        new_password     = data.get('new_password')
        current_password = data.get('current_password')

        # ── 2. Nothing to do? ──
        if not updates and not new_password:
            return Response(
                {"error": "No updatable fields provided."},
                status=status.HTTP_400_BAD_REQUEST
            )

        # ── 3. Basic length/blank validation ──
        for field, value in updates.items():
            if not isinstance(value, str) or not value.strip():
                return Response(
                    {"error": f"{field} must be a non-empty string."},
                    status=status.HTTP_400_BAD_REQUEST
                )

        # ── 4. Password change validation ──
        if new_password:
            if not current_password:
                return Response(
                    {"error": "current_password is required to set a new password."},
                    status=status.HTTP_400_BAD_REQUEST
                )
            if len(new_password) < 8:
                return Response(
                    {"error": "New password must be at least 8 characters."},
                    status=status.HTTP_400_BAD_REQUEST
                )

            with connection.cursor() as cursor:
                cursor.execute(
                    "SELECT password FROM users_user WHERE id = %s", [user_id]
                )
                row = cursor.fetchone()

            if not row or not check_password(current_password, row[0]):
                return Response(
                    {"error": "Current password is incorrect."},
                    status=status.HTTP_400_BAD_REQUEST
                )
            updates['password'] = make_password(new_password)

        # ── 5. Build and run the UPDATE ──
        set_clause = ', '.join(f"{col} = %s" for col in updates)
        values     = list(updates.values()) + [user_id]

        try:
            with connection.cursor() as cursor:
                cursor.execute(
                    f"UPDATE users_user SET {set_clause} WHERE id = %s",
                    values
                )
                if cursor.rowcount == 0:
                    return Response(
                        {"error": "User not found."},
                        status=status.HTTP_404_NOT_FOUND
                    )
        except IntegrityError:
            return Response(
                {"error": "Phone number is already in use by another account."},
                status=status.HTTP_400_BAD_REQUEST
            )
        except Exception as e:
            return Response(
                {"error": str(e)},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )

        return Response(
            {"message": "Profile updated successfully."},
            status=status.HTTP_200_OK
        )

    def delete(self, request):
        """
        DELETE /api/auth/profile/
        Permanently deletes the authenticated user and all their data.
        """
        user_id = request.user.id
        try:
            with connection.cursor() as cursor:

                # 1. Get the customer.id
                cursor.execute(
                    "SELECT id FROM customers_customer WHERE user_id = %s", [user_id]
                )
                row = cursor.fetchone()
                customer_id = row[0] if row else None

                if customer_id:
                    # 2. Delete order items
                    cursor.execute("""
                        DELETE oi FROM orders_orderitem oi
                        INNER JOIN orders_order o ON o.order_id = oi.order_id
                        WHERE o.customer_id = %s
                    """, [customer_id])

                    # 3. Delete orders
                    cursor.execute(
                        "DELETE FROM orders_order WHERE customer_id = %s", [customer_id]
                    )

                    # 4. Delete delivery addresses — try both possible table names
                    for tbl in ('addresses_deliveryaddress', 'addresses_deliveryadress'):
                        try:
                            cursor.execute(
                                f"DELETE FROM {tbl} WHERE customer_id = %s", [customer_id]
                            )
                            break
                        except Exception:
                            connection.connection.rollback()  # clear failed statement in MySQL

                    # 5. Delete customer profile
                    cursor.execute(
                        "DELETE FROM customers_customer WHERE id = %s", [customer_id]
                    )

                # 6. Delete rider additional info then rider
                try:
                    cursor.execute("""
                        DELETE rai FROM riders_rider_additional_information rai
                        INNER JOIN riders_rider r ON r.id = rai.rider_id
                        WHERE r.user_id = %s
                    """, [user_id])
                except Exception:
                    connection.connection.rollback()

                cursor.execute("DELETE FROM riders_rider WHERE user_id = %s", [user_id])

                # 7. Delete restaurant discounts then restaurant
                try:
                    cursor.execute("""
                        DELETE d FROM resturants_discount d
                        INNER JOIN resturants_restaurant r ON r.id = d.resturant_id
                        WHERE r.user_id = %s
                    """, [user_id])
                except Exception:
                    connection.connection.rollback()

                cursor.execute("DELETE FROM resturants_restaurant WHERE user_id = %s", [user_id])

                # 8. Delete the user
                cursor.execute("DELETE FROM users_user WHERE id = %s", [user_id])

            return Response(
                {"message": "Account deleted successfully."},
                status=status.HTTP_200_OK
            )
        except Exception as e:
            return Response(
                {"error": str(e)},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR
            )

# ─────────────────────────────────────────────────────────────────────────────
# DELIVERY ADDRESS — saves the address the customer picks in the Header
# POST /api/auth/address/
# Called by Header.jsx confirmAddress() whenever user picks a delivery location
# ─────────────────────────────────────────────────────────────────────────────

class DeliveryAddressView(APIView):
    """
    POST /api/auth/address/
    
    Saves the delivery address the customer selected in the "Deliver to" header.
    Creates a new addresses_deliveryaddress row or updates the most recent HOME
    address if one already exists.

    Body: { address, latitude, longitude, type }
    - address   : full display name from Nominatim
    - latitude  : float or null
    - longitude : float or null
    - type      : 'delivery' (we store as HOME type)
    """
    permission_classes = [IsAuthenticated]

    def post(self, request):
        user_id  = request.user.id
        data     = request.data
        address  = (data.get('address') or '').strip()
        latitude = data.get('latitude')
        longitude= data.get('longitude')

        if not address:
            return Response(
                {"error": "address is required."},
                status=status.HTTP_400_BAD_REQUEST
            )

        with connection.cursor() as cursor:
            # Get customer_id
            cursor.execute(
                "SELECT id FROM customers_customer WHERE user_id = %s",
                [user_id]
            )
            row = cursor.fetchone()
            if not row:
                # Not a customer (could be rider/restaurant) — just return OK
                # No delivery address table for non-customers
                return Response({"message": "Address noted."}, status=status.HTTP_200_OK)

            customer_id = row[0]

            # Check if a HOME delivery address already exists
            cursor.execute("""
                SELECT id FROM addresses_deliveryaddress
                WHERE customer_id = %s AND address_type = 'HOME'
                LIMIT 1
            """, [customer_id])
            existing = cursor.fetchone()

            if existing:
                # Update existing HOME address with new location
                cursor.execute("""
                    UPDATE addresses_deliveryaddress
                    SET description  = %s,
                        latitude     = %s,
                        longitude    = %s
                    WHERE id = %s
                """, [address, latitude, longitude, existing[0]])
                return Response(
                    {"message": "Delivery address updated.", "address_id": existing[0]},
                    status=status.HTTP_200_OK
                )
            else:
                # Insert new HOME address
                cursor.execute("""
                    INSERT INTO addresses_deliveryaddress
                        (customer_id, address_type, street_number,
                         apartment_number, description, latitude, longitude)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                """, [
                    customer_id,
                    'HOME',
                    None,
                    None,
                    address,
                    latitude,
                    longitude,
                ])
                cursor.execute("SELECT LAST_INSERT_ID()")
                new_id = cursor.fetchone()[0]
                return Response(
                    {"message": "Delivery address saved.", "address_id": new_id},
                    status=status.HTTP_201_CREATED
                )