# Generated by Django 6.0 on 2026-01-13 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuisines', '0001_initial'),
        ('resturants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discount',
            name='resturant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='resturants.restaurant'),
        ),
        migrations.AddField(
            model_name='serve',
            name='cuisine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisines.cuisine'),
        ),
        migrations.AddField(
            model_name='serve',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resturants.restaurant'),
        ),
    ]
