# Generated by Django 6.0 on 2026-01-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
    ]
