# Generated by Django 6.0 on 2026-01-13 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0001_initial'),
        ('resturants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serve',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuisines.cuisine'),
        ),
        migrations.AlterField(
            model_name='serve',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturants.restaurant'),
        ),
    ]
