# Generated by Django 6.0 on 2026-01-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0003_alter_serve_cuisine_alter_serve_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
