# Generated by Django 6.0 on 2026-01-30 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0001_initial'),
        ('resturants', '0003_remove_restaurant_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serve',
            name='cuisine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuisines.cuisine'),
        ),
        migrations.AlterField(
            model_name='serve',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resturants.restaurant'),
        ),
    ]
