# Generated by Django 6.0 on 2026-01-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0004_alter_restaurant_user_alter_serve_cuisine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discount_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='discount',
            unique_together={('resturant', 'discount_num')},
        ),
    ]
