# Generated by Django 6.0 on 2026-01-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0004_alter_restaurant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='min_order',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
