# Generated by Django 6.0 on 2026-02-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0006_restaurant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
    ]
