# Generated by Django 6.0 on 2026-02-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0008_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_category',
            field=models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('FAST FOOD', 'Fast Food'), ('BAKERY', 'Bakery'), ('DESERT', 'Desert'), ('CLOUD', 'Cloud'), ('FOOD TRUCK', 'Food Truck'), ('CATERING', 'Catering')], default='RESTAURANT', max_length=50, null=True),
        ),
    ]
