# Generated by Django 6.0 on 2026-02-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0010_alter_restaurant_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
    ]
