# Generated by Django 6.0 on 2026-03-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturants', '0011_discount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_category',
            field=models.CharField(blank=True, choices=[('RESTAURANT', 'Restaurant'), ('CAFE', 'Cafe'), ('FAST FOOD', 'Fast Food'), ('BAKERY', 'Bakery'), ('DESERT', 'Dessert Shop'), ('CLOUD', 'Cloud Kitchen'), ('FOOD TRUCK', 'Food Truck'), ('CATERING', 'Catering Service')], default='RESTAURANT', max_length=50, null=True),
        ),
    ]
