# Generated by Django 6.0 on 2026-01-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemlist',
            name='price_at_purchage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
