# Generated by Django 6.0 on 2026-01-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_review_alter_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_longitude',
        ),
    ]
