# Generated by Django 6.0 on 2026-01-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_at_order_delivery_address_and_more'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reviews.review'),
        ),
    ]
