# Generated by Django 6.0 on 2026-03-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_charge_order_service_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_tip',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
