# Generated by Django 6.0 on 2026-01-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resturants', '0002_restaurant_alter_discount_resturant_delete_resturant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_ammount', models.FloatField()),
                ('discount_description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='items.item')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='resturants.restaurant')),
            ],
        ),
    ]
