# Generated by Django 6.0 on 2026-01-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_ammount', models.FloatField(null=True)),
                ('discount_description', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
