# Generated by Django 6.0 on 2026-01-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepare',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prepare',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepare',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prepare',
            name='discount_ammount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='prepare',
            name='discount_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
