# Generated by Django 6.0 on 2026-01-30 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0001_initial'),
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='cuisine',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='cuisines.cuisine'),
        ),
    ]
