# Generated by Django 6.0 on 2026-01-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_category_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='None/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
