# Generated by Django 6.0 on 2026-01-30 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisines', '0001_initial'),
        ('items', '0003_menuitem_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='cuisine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='cuisines.cuisine'),
        ),
    ]
