# Generated by Django 6.0 on 2026-02-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_menuitem_cuisine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='image_path',
            new_name='image',
        ),
    ]
