# Generated by Django 6.0 on 2026-01-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_remove_category_item_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
