# Generated by Django 6.0 on 2026-02-19 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_menuitem_image'),
        ('resturants', '0011_discount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='resturants.restaurant'),
        ),
    ]
