# Generated by Django 6.0 on 2026-02-19 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_category_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='discount_ammount',
            new_name='discount_amount',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.category'),
        ),
    ]
