# Generated by Django 6.0 on 2026-01-19 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_remove_address_id_remove_address_label_and_more'),
        ('users', '0003_alter_user_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address'),
        ),
    ]
