# Generated by Django 6.0 on 2026-01-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_review_alter_order_address'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('order', 'payment_num')},
        ),
    ]
