# Generated by Django 6.0 on 2026-01-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('vehicle', models.CharField(choices=[('BIKE', 'Motorbike'), ('CYCLE', 'Bicycle'), ('SCOOTER', 'Scooter')], max_length=50)),
                ('vehicle_pallete', models.CharField(max_length=50)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('currrent_longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
