# Generated by Django 6.0 on 2026-01-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('vehicle', models.CharField(choices=[('BI', 'bike'), ('CY', 'by-cycle'), ('CA', 'car')], max_length=2)),
            ],
        ),
    ]
