# Generated by Django 6.0 on 2026-03-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_rename_user_deliveryaddress_customer'),
        ('riders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider_Additional_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_front', models.ImageField(upload_to='')),
                ('nid_back', models.ImageField(upload_to='')),
                ('nid_number', models.CharField(max_length=50)),
                ('wallet_balace', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gender', models.CharField(max_length=10)),
                ('emergency_contact_name', models.CharField(max_length=20)),
                ('emergency_contact_number', models.CharField(max_length=20)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.address')),
                ('rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='riders.rider')),
            ],
        ),
    ]
