# Generated by Django 6.0 on 2026-01-13 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rider',
            old_name='currrent_longitude',
            new_name='current_longitude',
        ),
        migrations.RenameField(
            model_name='rider',
            old_name='vehicle_pallete',
            new_name='license_plate',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='address',
        ),
    ]
