# Generated by Django 6.0 on 2026-03-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0003_rider_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='verfied',
            field=models.IntegerField(default=0),
        ),
    ]
