# Generated by Django 6.0 on 2026-03-27 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riders', '0004_rider_verfied'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rider',
            table='riders_rider',
        ),
        migrations.AlterModelTable(
            name='rider_additional_information',
            table='riders_rider_additional_information',
        ),
    ]
