# Generated by Django 6.0 on 2026-03-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_deliveryadress'),
        ('customers', '0002_initial'),
        ('orders', '0007_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryAdress',
            new_name='DeliveryAddress',
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='customers.customer'),
        ),
    ]
