# Generated by Django 6.0 on 2026-03-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0003_rename_deliveryadress_deliveryaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='user',
            new_name='customer',
        ),
    ]
